name: Step 3, TBD-step-3-name

# This step triggers after TBD-step-3-event-desc.
# This workflow updates from step 3 to step 4.

# This will run every time we TBD-step-3-event-desc.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

#  check_results: #TODO
#    name: Check results
#    needs: get_current_step

  update_to_week4:
    name: Update to week 4
    needs: [get_current_step] #, check_results]

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # 2. The step is currently 3.
    # Reference: https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference: https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 3 
          && github.event_name == 'push' && github.ref == 'refs/heads/main'}}

    # We'll run Ubuntu for performance instead of Mac or Windows.
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.

      # In README.md, switch step 3 for step 4.
      - name: Update to step 4
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4
          #branch_name: tbd-branch-name

      - name: Create a new branch
        run: |
          echo "Make a branch"
          BRANCH=week4
          git checkout -b $BRANCH
          # copy the current README.md to week3
          cp .github/steps/3-loop_script.md week3/README.md
          git add week3/README.md      
          cp -r .github/working_dir/week4 .
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add week4/*
          git commit -m "Add step working directory for step 4"
          git push origin $BRANCH
          echo "Push"
          git push --set-upstream origin $BRANCH
          echo "Restore main"
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
